name: Deploy
on:
  push:
    branches: [step1, step2]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: 환경 변수 설정
        run: |
          echo "VITE_BASE_URL=$VITE_BASE_URL" >> .env
          echo "VITE_USER_ID=$VITE_USER_ID" >> .env
          echo "VITE_USER_PASSWORD=$VITE_USER_PASSWORD" >> .env
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_USER_ID: ${{ secrets.VITE_USER_ID }}
          VITE_USER_PASSWORD: ${{ secrets.VITE_USER_PASSWORD }}

      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
